export const SUBMIT_EXPERIENCE_SUCCESS = 'SUBMIT_EXPERIENCE_SUCCESS';
export const SUBMIT_EXPERIENCE_FAILURE = 'SUBMIT_EXPERIENCE_FAILURE';

export const FETCH_USER_APP_REQUEST = 'FETCH_USER_APP_REQUEST';
export const FETCH_USER_APP_SUCCESS = 'FETCH_USER_APP_SUCCESS';
export const FETCH_USER_APP_FAILURE = 'FETCH_USER_APP_FAILURE';

export const SET_USER_APP_STALE = 'SET_USER_APP_STALE';